name: Build .NET Solution

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: |
        for sln in Solutions/*.sln; do
          msbuild "$sln" -property:Configuration=Release
        done
