name: Build .NET Solution

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.5.1'

    - name: Build solution
      run: |
        $slns = Get-ChildItem Solutions/*.sln
        foreach ($sln in $slns) {
          msbuild $sln.FullName /p:Configuration=Release
        }
      shell: powershell
