name: Build .NET Solution

on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'


jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Install nuget dependencies
      run: nuget restore Snaffler.sln
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.5'

    - name: Build solution
      run: msbuild Snaffler.sln /p:Configuration=Release

