name: Build Snaffler

on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'


jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Install nuget dependencies
      run: nuget restore Solutions/Snaffler.sln

    - name: Build solution
      run: msbuild Solutions/Snaffler.sln /p:Configuration=Release

